/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mixedword;

import mixedword.Model.Grid;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Grid grid = new Grid(10,10);

    }
}
